version: '3.8'

services:
  postgres:
    container_name: hotellist-database
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "6543:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: hotellist-api
    depends_on:
      - postgres
    ports:
      - 5000:80
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=dotnet;Username=admin;Password=admin1234

volumes:
  postgres-db:
    driver: local

networks:
  postgres-network:
    driver: bridge
